#!/bin/bash

# can run diff to see if 2 files are different

if [ $# -eq 2 ]; then
    NOFLAG=1
    OUTFILE=$1
    INDIR=$2
elif [ $# -eq 3 ]; then
    NOFLAG=0
    FLAG=$1
    OUTFILE=$2
    INDIR=$3
else 
    echo "You gave me an incorrect number of args"
    exit 1
fi


if [ -d "${INDIR}" ]; then
    echo "Detected ${INDIR} as a directory"
    cp -R ${INDIR} ${OUTFILE}
    find ${OUTFILE} | ./findDuplicates.pl ${OUTFILE}
else
    echo "${INDIR} is not a directory"
    exit 1
fi


if [ ${NOFLAG} -eq 0 ]; then
    case "${FLAG}" in
        -g)
            echo "g flag detected: compressing with gzip"
            tar -zcf ${OUTFILE}.tar.gz ${OUTFILE}
            ;;
        -b)
            echo "b flag detected: compressing with bzip2"
            tar -jcf ${OUTFILE}.tar.bz2 ${OUTFILE}
            ;;
        -c)
            echo "c flag detected: compressing with compress"
            tar -cf ${OUTFILE}.tar ${OUTFILE} >> /dev/null
            compress -f ${OUTFILE}.tar #no need to apprend .Z, it is automatically appended
            ;; 
        *)
            echo "Unsupported flag detected"
            exit 1
            ;;
    esac
else 
    echo "handling no flags: leaving file as tar"
    tar -cvf ${OUTFILE}.tar ${OUTFILE}
fi
    