#!/bin/bash

# can run diff to see if 2 files are different

if [ $# -eq 2 ]; then
    FLAG=$1
    DIR=$2
else 
    echo "You gave me an incorrect number of args"
    exit 1
fi

if [[ $DIR =~ (.)*\.tar\.gz$ ]]; then
    echo "dir is gzip file"
    echo "base name is ${BASH_REMATCH[1]}"
    tar -zxf $DIR

elif [[ $DIR =~ (.)*\.tar\.bz2$ ]]; then
    echo "dir is bzip2 file"
    echo "base name is ${BASH_REMATCH[1]}"
    tar -jxf $DIR

elif [[ $DIR =~ (.)*\.tar\.Z$ ]]; then
    echo "dir is compress file"
    echo "base name is ${BASH_REMATCH[1]}"

elif [[ $DIR =~ (.)*\.tar$ ]]; then
    echo "dir is tar file"
    echo "base name is ${BASH_REMATCH[1]}"
    
else
    echo "Could not identify file type"
    exit 1
fi

case "${FLAG}" in
    -d)
        echo "d flag detected: deleting duplicate files"
        ;;
    -b)
        echo "l flag detected: unarchiving dupes as soft links"
        ;;
    -c)
        echo "c flag detected: unarchiving dupes as copies"
        ;; 
    *)
        echo "Unsupported flag detected"
        exit 1
        ;;
esac

    