#!/bin/bash

# can run diff to see if 2 files are different

if [ $# -eq 2 ]; then
    FLAG=$1
    DIR=$2
else 
    echo "You gave me an incorrect number of args"
    exit 1
fi

GZIP_REGEX="(.+)\.tar\.gz$"
BZIP2_REGEX="(.+)\.tar\.bz2$"
COMPRESS_REGEX="(.+)\.tar\.Z$"
TARFILE_REGEX="(.+)\.tar$"

if [[ $DIR =~ $GZIP_REGEX ]]; then
    BASENAME=${BASH_REMATCH[1]}
    echo "dir is gzip file"
    tar -zxf $DIR

elif [[ $DIR =~ $BZIP2_REGEX ]]; then
    BASENAME=${BASH_REMATCH[1]}
    echo "dir is bzip2 file"
    tar -jxf $DIR

elif [[ $DIR =~ $COMPRESS_REGEX ]]; then
    BASENAME=${BASH_REMATCH[1]}
    echo "dir is compress file"
    uncompress -c $DIR > ${BASENAME}.tar
    tar -xf ${BASENAME}.tar

elif [[ $DIR =~ $TARFILE_REGEX ]]; then
    BASENAME=${BASH_REMATCH[1]}
    echo "dir is tar file"
    tar -xf $DIR
    
else
    echo "Could not identify file type"
    exit 1
fi

DUPE_FILE_PATH=${BASENAME}/duplicates
case "${FLAG}" in
    -d)
        echo "d flag detected: deleting duplicate files"
        rm -f ${DUPE_FILE_PATH}
        exit 0
        ;;
    -l)
        echo "l flag detected: unarchiving dupes as soft links"
        ./src/createSoftlinks.pl ${DUPE_FILE_PATH}
        rm -f ${DUPE_FILE_PATH}
        exit 0
        ;; 
    -c)
        echo "c flag detected: unarchiving dupes as copies"
        ./src/createCopies.pl ${DUPE_FILE_PATH}
        rm -f ${DUPE_FILE_PATH}
        exit 0
        ;; 
    *)
        echo "Unsupported flag detected"
        exit 1
        ;;
esac

    